#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import StoreKit;
@import UIKit;
@import VOGOPlayerCore;
#endif

#import <VOGOPlayerUI/VOGOPlayerUI.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VOGOPlayerUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC12VOGOPlayerUI15ColorController")
@interface ColorController : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12VOGOPlayerUI12ColorUpdater")
@interface ColorUpdater : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12VOGOPlayerUI24KeyboardLayoutConstraint") SWIFT_AVAILABILITY(tvos,unavailable)
@interface KeyboardLayoutConstraint : NSLayoutConstraint
- (void)awakeFromNib SWIFT_AVAILABILITY(tvos,unavailable);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSString (SWIFT_EXTENSION(VOGOPlayerUI))
- (NSString * _Nonnull)vogoLocalizedWithTableName:(NSString * _Nullable)tableName SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12VOGOPlayerUI15PaymentObserver")
@interface PaymentObserver : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SKProductsRequest;
@class SKProductsResponse;

@interface PaymentObserver (SWIFT_EXTENSION(VOGOPlayerUI)) <SKProductsRequestDelegate>
- (void)productsRequest:(SKProductsRequest * _Nonnull)request didReceiveResponse:(SKProductsResponse * _Nonnull)response;
@end

@class SKRequest;

@interface PaymentObserver (SWIFT_EXTENSION(VOGOPlayerUI)) <SKRequestDelegate>
- (void)requestDidFinish:(SKRequest * _Nonnull)request;
- (void)request:(SKRequest * _Nonnull)request didFailWithError:(NSError * _Nonnull)error;
@end

@class SKPaymentQueue;
@class SKPaymentTransaction;
@class SKDownload;
@class SKPayment;
@class SKProduct;

@interface PaymentObserver (SWIFT_EXTENSION(VOGOPlayerUI)) <SKPaymentTransactionObserver>
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue updatedTransactions:(NSArray<SKPaymentTransaction *> * _Nonnull)transactions;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue removedTransactions:(NSArray<SKPaymentTransaction *> * _Nonnull)transactions;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue restoreCompletedTransactionsFailedWithError:(NSError * _Nonnull)error;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(SKPaymentQueue * _Nonnull)queue;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue updatedDownloads:(NSArray<SKDownload *> * _Nonnull)downloads;
- (BOOL)paymentQueue:(SKPaymentQueue * _Nonnull)queue shouldAddStorePayment:(SKPayment * _Nonnull)payment forProduct:(SKProduct * _Nonnull)product SWIFT_WARN_UNUSED_RESULT;
- (void)paymentQueueDidChangeStorefront:(SKPaymentQueue * _Nonnull)queue;
@end




@interface SKPaymentTransaction (SWIFT_EXTENSION(VOGOPlayerUI))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end



@protocol ThemeModifier;

SWIFT_CLASS("_TtC12VOGOPlayerUI5Store")
@interface Store : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Store * _Nonnull shared;)
+ (Store * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) PaymentObserver * _Nonnull paymentObserver;
@property (nonatomic, strong) id <ThemeModifier> _Nonnull themeController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC12VOGOPlayerUI17SwiftVGController")
@interface SwiftVGController : VGController
@property (nonatomic, readonly) BOOL prefersHomeIndicatorAutoHidden;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)updateDesyncLabel;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class VGPlayer;

@interface SwiftVGController (SWIFT_EXTENSION(VOGOPlayerUI))
- (void)player:(VGPlayer * _Nonnull)player eventType:(EventType)eventType values:(NSDictionary * _Nonnull)values;
@end

@class UIGestureRecognizer;

@interface SwiftVGController (SWIFT_EXTENSION(VOGOPlayerUI)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end











@class UITableView;
@class UITableViewCell;

@interface SwiftVGController (SWIFT_EXTENSION(VOGOPlayerUI)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface SwiftVGController (SWIFT_EXTENSION(VOGOPlayerUI)) <UITableViewDelegate>
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end









@class UIView;
@class UILabel;
@class UITextField;

SWIFT_PROTOCOL("_TtP12VOGOPlayerUI13ThemeModifier_")
@protocol ThemeModifier
- (void)pimpMyViewsWithViewsWithShadow:(NSArray<UIView *> * _Nullable)viewsWithShadow viewsWithBorder:(NSArray<UIView *> * _Nullable)viewsWithBorder roundedCorners:(NSArray<UIView *> * _Nullable)roundedCorners labelsWithFont:(NSArray<UILabel *> * _Nullable)labelsWithFont textviewsWithFont:(NSArray<UITextField *> * _Nullable)textviewsWithFont;
@end


SWIFT_CLASS("_TtC12VOGOPlayerUI14UIBundleHelper")
@interface UIBundleHelper : NSObject
+ (NSBundle * _Nullable)bundle SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface UIImage (SWIFT_EXTENSION(VOGOPlayerUI))
+ (UIImage * _Nullable)backgroundImage SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)header SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)logo SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)camera SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)file SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)moins15 SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)moins15Background SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)plus15 SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)markerPrevious SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)markerNext SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)plus15Background SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)play SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)pause SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)playSlow SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)recStart SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)recStop SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)controlBackground SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)close SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)fullScreen SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)lock SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)triangle SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)hourglass SWIFT_WARN_UNUSED_RESULT;
@end




@interface UIStoryboard (SWIFT_EXTENSION(VOGOPlayerUI))
+ (UIStoryboard * _Nonnull)vogoStoryboardFor:(Class _Nonnull)aClass SWIFT_WARN_UNUSED_RESULT;
@end








SWIFT_CLASS("_TtC12VOGOPlayerUI19VGCGUViewController")
@interface VGCGUViewController : UIViewController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
+ (BOOL)CGUValidated SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface VGCGUViewController (SWIFT_EXTENSION(VOGOPlayerUI))
+ (VGCGUViewController * _Nonnull)loadFromStoryboardWithStoryboard:(UIStoryboard * _Nonnull)storyboard SWIFT_WARN_UNUSED_RESULT;
@end






SWIFT_CLASS("_TtC12VOGOPlayerUI21VGLoginViewController")
@interface VGLoginViewController : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)tapOnBackground;
+ (BOOL)LoginValidated SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface VGLoginViewController (SWIFT_EXTENSION(VOGOPlayerUI)) <UIPickerViewDelegate>
@end


@interface VGLoginViewController (SWIFT_EXTENSION(VOGOPlayerUI))
+ (VGLoginViewController * _Nonnull)loadFromStoryboardWithStoryboard:(UIStoryboard * _Nonnull)storyboard SWIFT_WARN_UNUSED_RESULT;
@end


@interface VGLoginViewController (SWIFT_EXTENSION(VOGOPlayerUI)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end






@interface VGLoginViewController (SWIFT_EXTENSION(VOGOPlayerUI)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end

@class UIPickerView;

@interface VGLoginViewController (SWIFT_EXTENSION(VOGOPlayerUI)) <UIPickerViewDataSource>
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
@end

@class VOGOParameters;

SWIFT_CLASS("_TtC12VOGOPlayerUI20VGRootViewController")
@interface VGRootViewController : UIViewController
- (nonnull instancetype)initWithPlayer:(VGPlayer * _Nonnull)player params:(VOGOParameters * _Nonnull)params OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly, strong) UIViewController * _Nullable childViewControllerForHomeIndicatorAutoHidden;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface VGRootViewController (SWIFT_EXTENSION(VOGOPlayerUI)) <UINavigationControllerDelegate>
- (UIInterfaceOrientationMask)navigationControllerSupportedInterfaceOrientations:(UINavigationController * _Nonnull)navigationController SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;

SWIFT_CLASS("_TtC12VOGOPlayerUI14VOGOParameters")
@interface VOGOParameters : NSObject
@property (nonatomic) BOOL hideCGU;
@property (nonatomic) BOOL wIFIDefaultTextVisibility;
@property (nonatomic) BOOL debugEnabled;
@property (nonatomic) BOOL screenCaptureAllowed;
@property (nonatomic) BOOL isStandalone;
@property (nonatomic) BOOL withBackgroundAudio;
@property (nonatomic, copy) NSString * _Nonnull wifiDefaultText;
@property (nonatomic, copy) NSString * _Nullable iOSMediaPlayerTitle;
@property (nonatomic, copy) NSString * _Nonnull WIFIConnectingText;
@property (nonatomic, strong) UIColor * _Nullable primaryColor;
@property (nonatomic, strong) UIColor * _Nullable secondaryColor;
@property (nonatomic, strong) UIImage * _Nullable iOSMediaPlayerImage;
@property (nonatomic, strong) UIImage * _Nullable mainLogo;
@property (nonatomic, strong) UIImage * _Nullable backgroundImage;
@property (nonatomic, strong) UIImage * _Nullable sponsort1Logo;
@property (nonatomic, strong) UIImage * _Nullable sponsort2Logo;
@property (nonatomic, strong) UIImage * _Nullable sponsort3Logo;
@property (nonatomic, strong) UIImage * _Nullable sponsort4Logo;
@property (nonatomic, strong) UIImage * _Nullable eventLogo;
@property (nonatomic) BOOL mainLogoLocked;
@property (nonatomic) BOOL logo1Locked;
@property (nonatomic) BOOL logo2Locked;
@property (nonatomic) BOOL logo3Locked;
@property (nonatomic) BOOL logo4Locked;
@property (nonatomic) BOOL eventLogoLocked;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12VOGOPlayerUI9VogoTheme")
@interface VogoTheme : NSObject <ThemeModifier>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)pimpMyViewsWithViewsWithShadow:(NSArray<UIView *> * _Nullable)viewsWithShadow viewsWithBorder:(NSArray<UIView *> * _Nullable)viewsWithBorder roundedCorners:(NSArray<UIView *> * _Nullable)roundedCorners labelsWithFont:(NSArray<UILabel *> * _Nullable)labelsWithFont textviewsWithFont:(NSArray<UITextField *> * _Nullable)textviewsWithFont;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import StoreKit;
@import UIKit;
@import VOGOPlayerCore;
#endif

#import <VOGOPlayerUI/VOGOPlayerUI.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VOGOPlayerUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC12VOGOPlayerUI15ColorController")
@interface ColorController : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12VOGOPlayerUI12ColorUpdater")
@interface ColorUpdater : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12VOGOPlayerUI24KeyboardLayoutConstraint") SWIFT_AVAILABILITY(tvos,unavailable)
@interface KeyboardLayoutConstraint : NSLayoutConstraint
- (void)awakeFromNib SWIFT_AVAILABILITY(tvos,unavailable);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSString (SWIFT_EXTENSION(VOGOPlayerUI))
- (NSString * _Nonnull)vogoLocalizedWithTableName:(NSString * _Nullable)tableName SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12VOGOPlayerUI15PaymentObserver")
@interface PaymentObserver : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SKProductsRequest;
@class SKProductsResponse;

@interface PaymentObserver (SWIFT_EXTENSION(VOGOPlayerUI)) <SKProductsRequestDelegate>
- (void)productsRequest:(SKProductsRequest * _Nonnull)request didReceiveResponse:(SKProductsResponse * _Nonnull)response;
@end

@class SKRequest;

@interface PaymentObserver (SWIFT_EXTENSION(VOGOPlayerUI)) <SKRequestDelegate>
- (void)requestDidFinish:(SKRequest * _Nonnull)request;
- (void)request:(SKRequest * _Nonnull)request didFailWithError:(NSError * _Nonnull)error;
@end

@class SKPaymentQueue;
@class SKPaymentTransaction;
@class SKDownload;
@class SKPayment;
@class SKProduct;

@interface PaymentObserver (SWIFT_EXTENSION(VOGOPlayerUI)) <SKPaymentTransactionObserver>
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue updatedTransactions:(NSArray<SKPaymentTransaction *> * _Nonnull)transactions;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue removedTransactions:(NSArray<SKPaymentTransaction *> * _Nonnull)transactions;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue restoreCompletedTransactionsFailedWithError:(NSError * _Nonnull)error;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(SKPaymentQueue * _Nonnull)queue;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue updatedDownloads:(NSArray<SKDownload *> * _Nonnull)downloads;
- (BOOL)paymentQueue:(SKPaymentQueue * _Nonnull)queue shouldAddStorePayment:(SKPayment * _Nonnull)payment forProduct:(SKProduct * _Nonnull)product SWIFT_WARN_UNUSED_RESULT;
- (void)paymentQueueDidChangeStorefront:(SKPaymentQueue * _Nonnull)queue;
@end




@interface SKPaymentTransaction (SWIFT_EXTENSION(VOGOPlayerUI))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end



@protocol ThemeModifier;

SWIFT_CLASS("_TtC12VOGOPlayerUI5Store")
@interface Store : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Store * _Nonnull shared;)
+ (Store * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) PaymentObserver * _Nonnull paymentObserver;
@property (nonatomic, strong) id <ThemeModifier> _Nonnull themeController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC12VOGOPlayerUI17SwiftVGController")
@interface SwiftVGController : VGController
@property (nonatomic, readonly) BOOL prefersHomeIndicatorAutoHidden;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)updateDesyncLabel;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class VGPlayer;

@interface SwiftVGController (SWIFT_EXTENSION(VOGOPlayerUI))
- (void)player:(VGPlayer * _Nonnull)player eventType:(EventType)eventType values:(NSDictionary * _Nonnull)values;
@end

@class UIGestureRecognizer;

@interface SwiftVGController (SWIFT_EXTENSION(VOGOPlayerUI)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end











@class UITableView;
@class UITableViewCell;

@interface SwiftVGController (SWIFT_EXTENSION(VOGOPlayerUI)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface SwiftVGController (SWIFT_EXTENSION(VOGOPlayerUI)) <UITableViewDelegate>
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end









@class UIView;
@class UILabel;
@class UITextField;

SWIFT_PROTOCOL("_TtP12VOGOPlayerUI13ThemeModifier_")
@protocol ThemeModifier
- (void)pimpMyViewsWithViewsWithShadow:(NSArray<UIView *> * _Nullable)viewsWithShadow viewsWithBorder:(NSArray<UIView *> * _Nullable)viewsWithBorder roundedCorners:(NSArray<UIView *> * _Nullable)roundedCorners labelsWithFont:(NSArray<UILabel *> * _Nullable)labelsWithFont textviewsWithFont:(NSArray<UITextField *> * _Nullable)textviewsWithFont;
@end


SWIFT_CLASS("_TtC12VOGOPlayerUI14UIBundleHelper")
@interface UIBundleHelper : NSObject
+ (NSBundle * _Nullable)bundle SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






@interface UIImage (SWIFT_EXTENSION(VOGOPlayerUI))
+ (UIImage * _Nullable)backgroundImage SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)header SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)logo SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)camera SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)file SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)moins15 SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)moins15Background SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)plus15 SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)markerPrevious SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)markerNext SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)plus15Background SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)play SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)pause SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)playSlow SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)recStart SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)recStop SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)controlBackground SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)close SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)fullScreen SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)lock SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)triangle SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)hourglass SWIFT_WARN_UNUSED_RESULT;
@end




@interface UIStoryboard (SWIFT_EXTENSION(VOGOPlayerUI))
+ (UIStoryboard * _Nonnull)vogoStoryboardFor:(Class _Nonnull)aClass SWIFT_WARN_UNUSED_RESULT;
@end








SWIFT_CLASS("_TtC12VOGOPlayerUI19VGCGUViewController")
@interface VGCGUViewController : UIViewController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
+ (BOOL)CGUValidated SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface VGCGUViewController (SWIFT_EXTENSION(VOGOPlayerUI))
+ (VGCGUViewController * _Nonnull)loadFromStoryboardWithStoryboard:(UIStoryboard * _Nonnull)storyboard SWIFT_WARN_UNUSED_RESULT;
@end






SWIFT_CLASS("_TtC12VOGOPlayerUI21VGLoginViewController")
@interface VGLoginViewController : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)tapOnBackground;
+ (BOOL)LoginValidated SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface VGLoginViewController (SWIFT_EXTENSION(VOGOPlayerUI)) <UIPickerViewDelegate>
@end


@interface VGLoginViewController (SWIFT_EXTENSION(VOGOPlayerUI))
+ (VGLoginViewController * _Nonnull)loadFromStoryboardWithStoryboard:(UIStoryboard * _Nonnull)storyboard SWIFT_WARN_UNUSED_RESULT;
@end


@interface VGLoginViewController (SWIFT_EXTENSION(VOGOPlayerUI)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end






@interface VGLoginViewController (SWIFT_EXTENSION(VOGOPlayerUI)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end

@class UIPickerView;

@interface VGLoginViewController (SWIFT_EXTENSION(VOGOPlayerUI)) <UIPickerViewDataSource>
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
@end

@class VOGOParameters;

SWIFT_CLASS("_TtC12VOGOPlayerUI20VGRootViewController")
@interface VGRootViewController : UIViewController
- (nonnull instancetype)initWithPlayer:(VGPlayer * _Nonnull)player params:(VOGOParameters * _Nonnull)params OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly, strong) UIViewController * _Nullable childViewControllerForHomeIndicatorAutoHidden;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface VGRootViewController (SWIFT_EXTENSION(VOGOPlayerUI)) <UINavigationControllerDelegate>
- (UIInterfaceOrientationMask)navigationControllerSupportedInterfaceOrientations:(UINavigationController * _Nonnull)navigationController SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;

SWIFT_CLASS("_TtC12VOGOPlayerUI14VOGOParameters")
@interface VOGOParameters : NSObject
@property (nonatomic) BOOL hideCGU;
@property (nonatomic) BOOL wIFIDefaultTextVisibility;
@property (nonatomic) BOOL debugEnabled;
@property (nonatomic) BOOL screenCaptureAllowed;
@property (nonatomic) BOOL isStandalone;
@property (nonatomic) BOOL withBackgroundAudio;
@property (nonatomic, copy) NSString * _Nonnull wifiDefaultText;
@property (nonatomic, copy) NSString * _Nullable iOSMediaPlayerTitle;
@property (nonatomic, copy) NSString * _Nonnull WIFIConnectingText;
@property (nonatomic, strong) UIColor * _Nullable primaryColor;
@property (nonatomic, strong) UIColor * _Nullable secondaryColor;
@property (nonatomic, strong) UIImage * _Nullable iOSMediaPlayerImage;
@property (nonatomic, strong) UIImage * _Nullable mainLogo;
@property (nonatomic, strong) UIImage * _Nullable backgroundImage;
@property (nonatomic, strong) UIImage * _Nullable sponsort1Logo;
@property (nonatomic, strong) UIImage * _Nullable sponsort2Logo;
@property (nonatomic, strong) UIImage * _Nullable sponsort3Logo;
@property (nonatomic, strong) UIImage * _Nullable sponsort4Logo;
@property (nonatomic, strong) UIImage * _Nullable eventLogo;
@property (nonatomic) BOOL mainLogoLocked;
@property (nonatomic) BOOL logo1Locked;
@property (nonatomic) BOOL logo2Locked;
@property (nonatomic) BOOL logo3Locked;
@property (nonatomic) BOOL logo4Locked;
@property (nonatomic) BOOL eventLogoLocked;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12VOGOPlayerUI9VogoTheme")
@interface VogoTheme : NSObject <ThemeModifier>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)pimpMyViewsWithViewsWithShadow:(NSArray<UIView *> * _Nullable)viewsWithShadow viewsWithBorder:(NSArray<UIView *> * _Nullable)viewsWithBorder roundedCorners:(NSArray<UIView *> * _Nullable)roundedCorners labelsWithFont:(NSArray<UILabel *> * _Nullable)labelsWithFont textviewsWithFont:(NSArray<UITextField *> * _Nullable)textviewsWithFont;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
